<?
$PERM["video"]["*"]="R";
$PERM["online"]["*"]="R";
$PERM["desktop_app"]["*"]="R";
$PERM["rasprodazha"]["2"]="D";
$PERM["rasprodazha"]["5"]="D";
$PERM["rasprodazha"]["3"]="D";
$PERM["rasprodazha"]["4"]="D";
$PERM["rasprodazha"]["6"]="D";
$PERM["rasprodazha"]["7"]="D";
$PERM["rasprodazha"]["*"]="D";
$PERM["import"]["*"]="D";
$PERM["alt.php"]["*"]="D";
$PERM["personal"]["7"]="W";
$PERM["catalog"]["7"]="W";
$PERM["news"]["7"]="W";
$PERM["about"]["7"]="W";
$PERM["index.php"]["7"]="W";
$PERM["/"]["*"]="R";
?>