<?
require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/header.php");
$APPLICATION->SetPageProperty("description", "Основные категории продукции на сайте belwooddoors.ru. Входные двери, межкомнатные, фурнитура");
$APPLICATION->SetPageProperty("keywords", "Каталог продукции, belwooddoors.ru");
$APPLICATION->SetPageProperty("title", "Каталог продукции на belwooddoors.ru");
$APPLICATION->SetTitle("Каталог продукции");
?>

<? $GLOBALS['sale_filter'] = array(
    "SECTION_ID" => 35, array(
        'LOGIC' => 'OR',
        array('>PROPERTY_OLD_PRICE' => 0),
        array('=ID' => CIBlockElement::SubQuery('PROPERTY_CML2_LINK', array(
            'IBLOCK_ID' => IBLOCK_ID_OFFERS,
            'ACTIVE' => 'Y',
            '>PROPERTY_OLD_PRICE' => 0
        )))
    )
);

global $arFilter123;
$arFilter123['!=PRICE_1'] = false;

CModule::IncludeModule("fileman");
$isMobileDevice = CLightHTMLEditor::IsMobileDevice();
$pageCount = $isMobileDevice ? 24 : 24;
?>
    <section class="catalog catalog--main">
        <div class="content-container">
            <? $APPLICATION->IncludeComponent(
	"bitrix:catalog", 
	"catalog", 
	array(
		"ACTION_VARIABLE" => "action",
		"ADD_ELEMENT_CHAIN" => "Y",
		"ADD_PICT_PROP" => "MORE_PHOTO",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"ADD_SECTIONS_CHAIN" => "Y",
		"ADD_SECTION_CHAIN" => "Y",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"ALSO_BUY_ELEMENT_COUNT" => "4",
		"ALSO_BUY_MIN_BUYES" => "1",
		"BASKET_URL" => "/personal/cart/",
		"BIG_DATA_RCM_TYPE" => "bestsell",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "3600",
		"CACHE_TYPE" => "N",
		"COMMON_ADD_TO_BASKET_ACTION" => "",
		"COMMON_SHOW_CLOSE_POPUP" => "N",
		"COMPARE_ELEMENT_SORT_FIELD" => "",
		"COMPARE_ELEMENT_SORT_ORDER" => "",
		"COMPARE_FIELD_CODE" => array(
			0 => "ID",
			1 => "CODE",
			2 => "XML_ID",
			3 => "NAME",
			4 => "TAGS",
			5 => "SORT",
			6 => "PREVIEW_TEXT",
			7 => "PREVIEW_PICTURE",
			8 => "DETAIL_TEXT",
			9 => "DETAIL_PICTURE",
			10 => "DATE_ACTIVE_FROM",
			11 => "ACTIVE_FROM",
			12 => "DATE_ACTIVE_TO",
			13 => "ACTIVE_TO",
			14 => "SHOW_COUNTER",
			15 => "SHOW_COUNTER_START",
			16 => "IBLOCK_TYPE_ID",
			17 => "IBLOCK_ID",
			18 => "IBLOCK_CODE",
			19 => "IBLOCK_NAME",
			20 => "IBLOCK_EXTERNAL_ID",
			21 => "DATE_CREATE",
			22 => "CREATED_BY",
			23 => "CREATED_USER_NAME",
			24 => "TIMESTAMP_X",
			25 => "MODIFIED_BY",
			26 => "USER_NAME",
			27 => "",
		),
		"COMPARE_NAME" => "CATALOG_COMPARE_LIST",
		"COMPARE_OFFERS_FIELD_CODE" => array(
			0 => "ID",
			1 => "CODE",
			2 => "XML_ID",
			3 => "NAME",
			4 => "TAGS",
			5 => "SORT",
			6 => "PREVIEW_TEXT",
			7 => "PREVIEW_PICTURE",
			8 => "DETAIL_TEXT",
			9 => "DETAIL_PICTURE",
			10 => "DATE_ACTIVE_FROM",
			11 => "ACTIVE_FROM",
			12 => "DATE_ACTIVE_TO",
			13 => "ACTIVE_TO",
			14 => "SHOW_COUNTER",
			15 => "SHOW_COUNTER_START",
			16 => "IBLOCK_TYPE_ID",
			17 => "IBLOCK_ID",
			18 => "IBLOCK_CODE",
			19 => "IBLOCK_NAME",
			20 => "IBLOCK_EXTERNAL_ID",
			21 => "DATE_CREATE",
			22 => "CREATED_BY",
			23 => "CREATED_USER_NAME",
			24 => "TIMESTAMP_X",
			25 => "MODIFIED_BY",
			26 => "USER_NAME",
			27 => "",
		),
		"COMPARE_OFFERS_PROPERTY_CODE" => array(
			0 => "COLOR",
			1 => "GLASS_COLOR",
			2 => "COLOR_IN",
			3 => "COLOR_OUT",
			4 => "ARTICLE",
			5 => "SIZE_DOOR",
			6 => "SIDE",
			7 => "WIDTH_PANEL",
			8 => "SIZE",
            9 => "HARDWARE_COLOR",
			10 => "",
		),
		"COMPARE_POSITION" => "top left",
		"COMPARE_POSITION_FIXED" => "N",
		"COMPARE_PROPERTY_CODE" => array(
			0 => "PRODUCT_TYPE",
			1 => "MATERIAL",
			2 => "STYLE",
			3 => "TYPE",
			4 => "NEWPRODUCT",
			5 => "SALELEADER",
			6 => "FLOOR_COLOR",
			7 => "GLASS_REF",
			8 => "BLOG_POST_ID",
			9 => "GUARANTEE",
			10 => "BOX_SQUARE",
			11 => "BLOG_COMMENTS_CNT",
			12 => "GLASS",
			13 => "DECORATION",
			14 => "MANUFACTURER",
			15 => "FLOOR_SIZE",
			16 => "GLASS_TYPE",
			17 => "COUNTRY",
			18 => "WIDTH",
			19 => "FURNITURE",
			20 => "SPECIALOFFER",
			21 => "TRANSOMS",
			22 => "BOX",
			23 => "JAMB",
			24 => "BAR",
			25 => "",
		),
		"COMPONENT_TEMPLATE" => "catalog",
		"CONVERT_CURRENCY" => "Y",
		"CURRENCY_ID" => MAIN_CURRENCY,
		"DETAIL_ADD_DETAIL_TO_SLIDER" => "N",
		"DETAIL_ADD_TO_BASKET_ACTION" => array(
		),
		"DETAIL_BACKGROUND_IMAGE" => "-",
		"DETAIL_BLOG_EMAIL_NOTIFY" => "N",
		"DETAIL_BLOG_URL" => "catalog_comments",
		"DETAIL_BLOG_USE" => "Y",
		"DETAIL_BRAND_PROP_CODE" => array(
			0 => "",
			1 => "",
		),
		"DETAIL_BRAND_USE" => "N",
		"DETAIL_BROWSER_TITLE" => "-",
		"DETAIL_CHECK_SECTION_ID_VARIABLE" => "N",
		"DETAIL_DETAIL_PICTURE_MODE" => "IMG",
		"DETAIL_DISPLAY_NAME" => "N",
		"DETAIL_DISPLAY_PREVIEW_TEXT_MODE" => "H",
		"DETAIL_FB_APP_ID" => "",
		"DETAIL_FB_USE" => "N",
		"DETAIL_META_DESCRIPTION" => "-",
		"DETAIL_META_KEYWORDS" => "-",
		"DETAIL_OFFERS_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"DETAIL_OFFERS_PROPERTY_CODE" => array(
			0 => "COLOR",
			1 => "GLASS_COLOR",
			2 => "COLOR_IN",
			3 => "COLOR_OUT",
			4 => "TRANSOMS",
			5 => "BOX",
			6 => "JAMB",
			7 => "BAR",
			8 => "SIZE_DOOR",
			9 => "OLD_PRICE",
			10 => "SIDE",
			11 => "WIDTH_PANEL",
			12 => "SIZE",
            13 => "HARDWARE_COLOR",
			14 => "",
		),
		"DETAIL_PROPERTY_CODE" => array(
			0 => "MATERIAL",
			1 => "STYLE",
			2 => "TYPE",
			3 => "Filling",
			4 => "structure",
			5 => "inside",
			6 => "COLLECTION",
			7 => "FLOOR_COLOR",
			8 => "GUARANTEE",
			9 => "GLASS",
			10 => "DECORATION",
			11 => "MANUFACTURER",
			12 => "FLOOR_SIZE",
			13 => "GLASS_TYPE",
			14 => "COUNTRY",
			15 => "WIDTH",
			16 => "Exterior_finish",
			17 => "Vneshnyaya_panel",
			18 => "Vnutrennyaya_otdelka",
			19 => "Vnutrennyaya_panel",
			20 => "Glazok",
			21 => "Dvernyye_petli_tip",
			22 => "Deviatory",
			23 => "Zamok_dopolnitelnyy",
			24 => "Zamok_osnovnoy",
			25 => "Klass_zashchity",
			26 => "Klass_zashchity_osnovnogo_zamka",
			27 => "Kolichestvo_zamkov",
			28 => "KOL_KON_YP",
			29 => "Kolichestvo_petel",
			30 => "Komplektatsiya",
			31 => "KONSTRUKCII",
			32 => "Nochnoy_zamok",
			33 => "Oblast_primeneniya",
			34 => "Otkryvaniye",
			35 => "Protivosyemnyye_rigeli",
			36 => "Rebra_zhestkosti",
			37 => "Regulyator_pritvora",
			38 => "Handles",
			39 => "TERMORAZRV",
			40 => "Tip_dopolnitelnogo_zamka",
			41 => "Tip_osnovnogo_zamka",
			42 => "tolshchina_korobki",
			43 => "Tolshchina_metalla_korobki",
			44 => "Tolshchina_metalla_polotna",
			45 => "Tolshchina_polotna",
			46 => "Ugol_otkryvaniya",
			47 => "Uteplitel_korobki",
			48 => "Tsvet_vneshney_korobki",
			49 => "Tsvet_vneshney",
			50 => "Tsvet_vnutrenney_korobki",
			51 => "Tsvet_vnutrenney",
			52 => "COLOR",
			53 => "SIZE_DOOR",
			54 => "WIDTH_PANEL",
			55 => "BREND_L_EXCHANGE",
			56 => "TSVET_L_EXCHANGE",
			57 => ""
		),
		"DETAIL_SET_CANONICAL_URL" => "N",
		"DETAIL_SET_VIEWED_IN_COMPONENT" => "Y",
		"DETAIL_SHOW_BASIS_PRICE" => "Y",
		"DETAIL_SHOW_MAX_QUANTITY" => "Y",
		"DETAIL_STRICT_SECTION_CHECK" => "Y",
		"DETAIL_USE_COMMENTS" => "Y",
		"DETAIL_USE_VOTE_RATING" => "N",
		"DETAIL_VK_USE" => "N",
		"DETAIL_VOTE_DISPLAY_AS_RATING" => "rating",
		"DISABLE_INIT_JS_IN_COMPONENT" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_ELEMENT_SELECT_BOX" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"ELEMENT_SORT_FIELD" => "SORT",
		"ELEMENT_SORT_FIELD2" => "name",
		"ELEMENT_SORT_FIELD_BOX" => "SORT",
		"ELEMENT_SORT_FIELD_BOX2" => "property_MINIMUM_PRICE",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_ORDER2" => "asc",
		"ELEMENT_SORT_ORDER_BOX" => "",
		"ELEMENT_SORT_ORDER_BOX2" => "",
		"FIELDS" => array(
			0 => "",
			1 => "",
		),
		"FILE_404" => "/404.php",
		"FILTER_FIELD_CODE" => array(
			0 => "",
			1 => "",
            2 => "MINIMUM_PRICE",
            3 => "MAXIMUM_PRICE",
        ),
		"FILTER_NAME" => "arFilter123",
		"FILTER_OFFERS_FIELD_CODE" => array(
			0 => "PREVIEW_PICTURE",
			1 => "DETAIL_PICTURE",
			2 => "",
		),
		"FILTER_OFFERS_PROPERTY_CODE" => array(
			0 => "COLOR",
			1 => "GLASS_COLOR",
			2 => "COLOR_IN",
			3 => "COLOR_OUT",
			4 => "ARTICLE",
			5 => "SIZE_DOOR",
			6 => "OLD_PRICE",
			7 => "WIDTH_PANEL",
			8 => "",
		),
		"FILTER_PRICE_CODE" => array(
			0 => "BASE",
		),
		"FILTER_PROPERTY_CODE" => array(
			0 => "FLOOR_COLOR",
			1 => "OLD_PRICE",
			2 => "SPECIALOFFER",
			3 => "MINIMUM_PRICE",
			4 => "MAXIMUM_PRICE",
		),
		"FILTER_VIEW_MODE" => "VERTICAL",
		"FORUM_ID" => "1",
		"GIFTS_DETAIL_BLOCK_TITLE" => "Выберите один из подарков",
		"GIFTS_DETAIL_HIDE_BLOCK_TITLE" => "N",
		"GIFTS_DETAIL_PAGE_ELEMENT_COUNT" => "3",
		"GIFTS_DETAIL_TEXT_LABEL_GIFT" => "Подарок",
		"GIFTS_MAIN_PRODUCT_DETAIL_BLOCK_TITLE" => "Выберите один из товаров, чтобы получить подарок",
		"GIFTS_MAIN_PRODUCT_DETAIL_HIDE_BLOCK_TITLE" => "N",
		"GIFTS_MAIN_PRODUCT_DETAIL_PAGE_ELEMENT_COUNT" => "3",
		"GIFTS_MESS_BTN_BUY" => "Выбрать",
		"GIFTS_SECTION_LIST_BLOCK_TITLE" => "Подарки к товарам этого раздела",
		"GIFTS_SECTION_LIST_HIDE_BLOCK_TITLE" => "N",
		"GIFTS_SECTION_LIST_PAGE_ELEMENT_COUNT" => "3",
		"GIFTS_SECTION_LIST_TEXT_LABEL_GIFT" => "Подарок",
		"GIFTS_SHOW_DISCOUNT_PERCENT" => "Y",
		"GIFTS_SHOW_IMAGE" => "Y",
		"GIFTS_SHOW_NAME" => "Y",
		"GIFTS_SHOW_OLD_PRICE" => "Y",
		"HIDE_NOT_AVAILABLE" => "N",
		"IBLOCK_ID" => "2",
		"IBLOCK_TYPE" => "catalog",
		"INCLUDE_SUBSECTIONS" => "Y",
		"INSTANT_RELOAD" => "N",
		"LABEL_PROP" => "-",
		"LINE_ELEMENT_COUNT" => "4",
		"LINK_ELEMENTS_URL" => "link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#",
		"LINK_IBLOCK_ID" => "12",
		"LINK_IBLOCK_TYPE" => "catalog",
		"LINK_PROPERTY_SID" => "CML2_LINK",
		"LIST_BROWSER_TITLE" => "-",
		"LIST_META_DESCRIPTION" => "-",
		"LIST_META_KEYWORDS" => "-",
		"LIST_OFFERS_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"LIST_OFFERS_LIMIT" => "500",
		"LIST_OFFERS_PROPERTY_CODE" => array(
			0 => "COLOR",
			1 => "GLASS_COLOR",
			2 => "SKLAD",
			3 => "COLOR_IN",
			4 => "COLOR_OUT",
			5 => "SIZE_DOOR",
			6 => "OLD_PRICE",
			7 => "WIDTH_PANEL",
			8 => "SIZE",
            9 => "HARDWARE_COLOR",
			10 => "",
		),
		"LIST_PROPERTY_CODE" => array(
			0 => "TYPE",
			1 => "SPECIALOFFER",
			2 => "COLOR",
			3 => "",
		),
		"MAIN_TITLE" => "Наличие на складах",
		"MESSAGES_PER_PAGE" => "10",
		"MESSAGE_404" => "",
		"MESS_BTN_ADD_TO_BASKET" => "В корзину",
		"MESS_BTN_BUY" => "Купить",
		"MESS_BTN_COMPARE" => "Сравнение",
		"MESS_BTN_DETAIL" => "Подробнее",
		"MESS_NOT_AVAILABLE" => "Нет в наличии",
		"MIN_AMOUNT" => "10",
		"OFFERS_CART_PROPERTIES" => array(
			0 => "COLOR",
			1 => "ARTICLE",
			2 => "SIZE",
            3 => "HARDWARE_COLOR"
		),
		"OFFERS_SORT_FIELD" => "SORT",
		"OFFERS_SORT_FIELD2" => "catalog_PRICE_1",
		"OFFERS_SORT_ORDER" => "asc",
		"OFFERS_SORT_ORDER2" => "asc",
		"OFFER_ADD_PICT_PROP" => "-",
		"OFFER_TREE_PROPS" => array(
			0 => "COLOR",
			1 => "GLASS_COLOR",
			2 => "COLOR_OUT",
			3 => "COLOR_IN",
			4 => "SIDE",
			5 => "SIZE_DOOR",
			6 => "WIDTH_PANEL",
			7 => "SIZE",
            8 => "HARDWARE_COLOR"
		),
		"PAGER_BASE_LINK_ENABLE" => "Y",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "3600",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "arrows_catalog",
		"PAGER_TITLE" => "Товары",
		"PAGE_ELEMENT_COUNT" => $pageCount,
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"PATH_TO_SMILE" => "/bitrix/images/forum/smile/",
		"PRICE_CODE" => array(
			0 => "BASE",
		),
		"PRICE_VAT_INCLUDE" => "Y",
		"PRICE_VAT_SHOW_VALUE" => "N",
		"PRODUCT_DISPLAY_MODE" => "Y",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRODUCT_PROPERTIES" => array(
		),
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"QUANTITY_FLOAT" => "N",
		"REVIEW_AJAX_POST" => "Y",
		"SECTIONS_HIDE_SECTION_NAME" => "Y",
		"SECTIONS_SHOW_PARENT_NAME" => "Y",
		"SECTIONS_VIEW_MODE" => "TILE",
		"SECTION_ADD_TO_BASKET_ACTION" => "ADD",
		"SECTION_BACKGROUND_IMAGE" => "-",
		"SECTION_COUNT_ELEMENTS" => "Y",
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"SECTION_TOP_DEPTH" => "1",
		"SEF_FOLDER" => "/catalog/",
		"SEF_MODE" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"SET_STATUS_404" => "Y",
		"SET_TITLE" => "Y",
		"SHOW_404" => "Y",
		"SHOW_DEACTIVATED" => "Y",
		"SHOW_DISCOUNT_PERCENT" => "Y",
		"SHOW_EMPTY_STORE" => "Y",
		"SHOW_GENERAL_STORE_INFORMATION" => "N",
		"SHOW_LINK_TO_FORUM" => "Y",
		"SHOW_OLD_PRICE" => "Y",
		"SHOW_PRICE_COUNT" => "",
		"SHOW_TOP_ELEMENTS" => "N",
		"SIDEBAR_DETAIL_SHOW" => "N",
		"SIDEBAR_PATH" => "/catalog/sidebar.php",
		"SIDEBAR_SECTION_SHOW" => "N",
		"STORES" => "",
		"STORE_PATH" => "/store/#store_id#",
		"TEMPLATE_THEME" => "",
		"TOP_ADD_TO_BASKET_ACTION" => "ADD",
		"TOP_ELEMENT_COUNT" => "16",
		"TOP_ELEMENT_SORT_FIELD" => "sort",
		"TOP_ELEMENT_SORT_FIELD2" => "id",
		"TOP_ELEMENT_SORT_ORDER" => "asc",
		"TOP_ELEMENT_SORT_ORDER2" => "desc",
		"TOP_LINE_ELEMENT_COUNT" => "4",
		"TOP_OFFERS_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"TOP_OFFERS_LIMIT" => "0",
		"TOP_OFFERS_PROPERTY_CODE" => array(
			0 => "ARTICLE",
			1 => "SIZE",
			2 => "COLOR",
			3 => "GLASS_COLOR",
            4 => "HARDWARE_COLOR",
			5 => "",
		),
		"TOP_PROPERTY_CODE" => array(
			0 => "NEWPRODUCT",
			1 => "SALELEADER",
			2 => "SPECIALOFFER",
			3 => "GLASS_REF",
			4 => "GLASS",
			5 => "MINIMUM_PRICE",
			6 => "MAXIMUM_PRICE",
			7 => "MATERIAL",
			8 => "COLOR",
			9 => "",
		),
		"TOP_VIEW_MODE" => "SECTION",
		"URL_TEMPLATES_READ" => "",
		"USER_FIELDS" => array(
			0 => "",
			1 => "",
		),
		"USE_ALSO_BUY" => "N",
		"USE_BIG_DATA" => "N",
		"USE_CAPTCHA" => "Y",
		"USE_COMMON_SETTINGS_BASKET_POPUP" => "N",
		"USE_COMPARE" => "Y",
		"USE_ELEMENT_COUNTER" => "Y",
		"USE_FILTER" => "Y",
		"USE_GIFTS_DETAIL" => "N",
		"USE_GIFTS_MAIN_PR_SECTION_LIST" => "Y",
		"USE_GIFTS_SECTION" => "Y",
		"USE_MAIN_ELEMENT_SECTION" => "N",
		"USE_MIN_AMOUNT" => "N",
		"USE_PRICE_COUNT" => "N",
		"USE_PRODUCT_QUANTITY" => "Y",
		"USE_REVIEW" => "Y",
		"USE_SALE_BESTSELLERS" => "N",
		"USE_STORE" => "N",
		"USE_STORE_PHONE" => "Y",
		"USE_STORE_SCHEDULE" => "Y",
		"HIDE_NOT_AVAILABLE_OFFERS" => "N",
		"USER_CONSENT" => "N",
		"USER_CONSENT_ID" => "0",
		"USER_CONSENT_IS_CHECKED" => "Y",
		"USER_CONSENT_IS_LOADED" => "N",
		"SHOW_SKU_DESCRIPTION" => "N",
		"PAGER_BASE_LINK" => "",
		"PAGER_PARAMS_NAME" => "arrPager",
		"COMPATIBLE_MODE" => "Y",
		"SEF_URL_TEMPLATES" => array(
			"sections" => "",
			"section" => "#SECTION_CODE_PATH#/",
			"element" => "#SECTION_CODE_PATH#/#ELEMENT_CODE#/",
			"compare" => "compare/",
			"smart_filter" => "#SECTION_CODE_PATH#/filter/#SMART_FILTER_PATH#/apply/",
		)
	),
	false
); ?><br>
            <br>
        </div>
    </section> <br><? require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/footer.php"); ?>